---
- name: include secret vars
  include_vars: secret.yml

- name: install packages
  apt:
    name:
      - motion
      - python-pip
      - python-setuptools
      - build-essential
      - libssl-dev
      - libffi-dev
      - python-dev
      - vim
      - inotify-tools

- name: install gsutil
  pip:
    name: gsutil

- name: upgrade pyasn1
  pip:
    name: pyasn1-modules
    state: latest # noqa 403

- name: set gcp credentials
  template:
    src: credentials.json.j2
    dest: /root/.credentials.json

- name: copy upload script
  copy:
    src: upload.sh
    dest: /root/bin/upload.sh
    mode: 0755

- name: copy upload.service
  copy:
    src: upload.service
    dest: /etc/systemd/system
    mode: 0644

- name: copy motion.conf
  copy:
    src: motion.conf
    dest: /etc/motion/motion.conf
    mode: 0644
    owner: root
    group: root

- name: update motion daemon setting
  replace:
    path: /etc/default/motion
    regexp: ^start_motion_daemon=no
    replace: start_motion_daemon=yes

- name: enable upload service
  systemd:
    name: upload
    enabled: yes
    state: started
    daemon_reload: yes

- name: enable motion service
  systemd:
    name: motion
    enabled: yes
    state: started
