---
- name: install nfs-server
  apt:
    name: nfs-kernel-server
    update_cache: yes

- name: create nfs directory
  file:
    path: /opt/nfs
    owner: nobody
    group: nogroup
    mode: 0755
    state: directory

- name: create nfs sub directory
  file:
    path: "/opt/nfs/{{ item }}"
    owner: nobody
    group: nogroup
    mode: 0755
    state: directory
  with_sequence: start=1 end=10 format=pv%02d

- name: copy exports
  copy:
    src: exports
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644

- name: enable nfs-server
  systemd:
    name: nfs-server
    enabled: yes
    state: started
    daemon_reload: yes
