---
- name: download node_exporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-armv7.tar.gz
    dest: /opt
    remote_src: yes
  register: download

- name: create link
  file:
    src: /opt/node_exporter-1.1.2.linux-armv7/node_exporter
    dest: /usr/bin/node_exporter
    state: link
    force: yes
  when: download.changed

# NOTE: old
# - name: copy self build file
#   copy:
#     src: node_exporter
#     dest: /usr/bin/node_exporter
#     owner: root
#     group: root
#     mode: 0755

- name: copy systemd file
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644

- name: enabled and start node_exporter service
  systemd:
    name: node_exporter
    enabled: yes
    state: restarted
    daemon_reload: yes
