route:
  receiver: 'default'
receivers:
- name: 'default'
  slack_configs:
    - api_url: '{{ slack_webhook_url }}'
      pretext: '<!channel>'
      text: {{ '"{{ .CommonAnnotations.summary }}"' }}
      send_resolved: true
