global:
  scrape_interval:     60s # By default, scrape targets every 15 seconds.
  evaluation_interval: 60s # By default, scrape targets every 15 seconds.
  external_labels:
      monitor: 'pikube'

rule_files:
  - alert.yml
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['localhost:9093']
scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets:
        - 192.168.99.100:9100
        labels:
          node_name: pikube01
      - targets:
        - 192.168.99.101:9100
        labels:
          node_name: pikube02
      - targets:
        - 192.168.99.102:9100
        labels:
          node_name: pikube03
      - targets:
        - 192.168.99.103:9100
        labels:
          node_name: pikube04
      - targets:
        - 192.168.99.5:9100
        labels:
          node_name: prometheus
  - job_name: kubernetes
    static_configs:
      - targets:
        - 192.168.99.200:8080
remote_write:
  - url: 'https://metric-api.newrelic.com/prometheus/v1/write?X-License-Key={{ newrelic_license_key }}&prometheus_server=prometheus'
